name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-17@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --json-file-output=snyk.json

      # - name: Upload Snyk report (.sarif)
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: snyk.sarif

      - name: Generate Snyk html report
        run: |
          npm install -g snyk snyk-to-html
          snyk-to-html -o snyk.html < snyk.json
          
      - name: Upload Snyk report
        uses: actions/upload-artifact@v4
        with: 
          name: snyk-report
          path: ./snyk.html

  spotbugs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: mvn clean package

      - name: Run SpotBugs
        run: mvn com.github.spotbugs:spotbugs-maven-plugin:4.7.3.3:spotbugs

      - name: Upload SpotBugs HTML report
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-html-report
          path: ./target/spotbugs.html
